"""Held-out intake cases. Gold lists EVERYTHING the text states (a confident fact not in gold counts as wrong).
AUTHORED BY THE DEVELOPER AFTER SEEING THE v1 FAILURES, so v2 is favoured. Not an advocate- or user-sourced set.
Hindi and Tamil lines need a native reader. keys: gold slots; tent = tentative suggestions that would be correct;
conflict = slots that must be reported as a conflict. For 'needs', gold is only checked when given."""
C = []
def case(text, tent=None, conflict=(), **gold): C.append(dict(text=text, tent=tent or {}, conflict=set(conflict), gold=gold))

# plain statements (the lexicon should handle these)
case("I am Hindu, my husband deserted me, I need divorce and maintenance", law="hindu", claimant="wife", needs=["divorce", "maintenance"], ground="desertion")
case("Muslim wife wants maintenance, my husband is in Dubai", law="muslim", claimant="wife", needs=["maintenance"], respondent_abroad=True)
case("I am a Christian husband, my wife and I want mutual divorce, separated 3 years", law="christian", claimant="husband", needs=["divorce"], mutual_consent=True, separated_months=36)
case("Parsi couple, married 3 years, mutual consent divorce", law="parsi", needs=["divorce"], mutual_consent=True, marriage_years=3)
case("Special Marriage Act, my husband beats me and I need protection", law="special_marriage", claimant="wife", needs=["protection"], domestic_violence=True)
case("married 4 years, separated 14 months, Hindu, mutual consent divorce", law="hindu", needs=["divorce"], mutual_consent=True, marriage_years=4, separated_months=14)
case("I am a divorced Hindu woman and need maintenance", law="hindu", needs=["maintenance"], divorce_status="decreed")
case("my divorce case is pending in court, I am Hindu", law="hindu", divorce_status="pending")
# negation and traps (v1 got these wrong)
case("My husband never hit me", claimant="wife", domestic_violence=False)
case("He didn't beat me but he left home 3 years ago, I am Hindu", law="hindu", domestic_violence=False, ground="desertion", separated_months=36)
case("There is no violence, we just want a mutual divorce, Hindu", law="hindu", domestic_violence=False, mutual_consent=True, needs=["divorce"])
case("he does not stop beating me, Christian wife", law="christian", domestic_violence=True, needs=["protection"])
case("I do not want divorce, I only need maintenance. Hindu wife. my husband is abroad", law="hindu", claimant="wife", needs=["maintenance"], respondent_abroad=True)
case("Not Hindu, we are Muslim", law="muslim")
case("My husband is not abroad, he lives in Pune. Hindu", law="hindu", claimant="wife", respondent_abroad=False)
case("I follow the affairs of state in the news. Hindu wife needs maintenance", law="hindu", needs=["maintenance"])
case("We have mutual friends, but he refuses to give a divorce. Hindu, my husband", law="hindu", claimant="wife", needs=["divorce"], mutual_consent=False)
case("I am Hindu and my husband is Muslim", conflict=["law"], claimant="wife")
case("My wife is Christian, I am Hindu, we want divorce", conflict=["law"], claimant="husband", needs=["divorce"])
# Hindi, Tamil, romanised
case("शादी को 5 साल हुए, 2 साल से अलग रह रहे हैं, हम हिंदू हैं, आपसी सहमति से तलाक", law="hindu", needs=["divorce"], mutual_consent=True, marriage_years=5, separated_months=24)
case("मेरे पति मुझे रोज़ मारते हैं, मैं मुस्लिम हूँ, मुझे गुजारा चाहिए", law="muslim", claimant="wife", domestic_violence=True, needs=["maintenance", "protection"])
case("मैं हिंदू हूँ, मेरे पति मुझे मारपीट नहीं करते, तलाक चाहिए", law="hindu", claimant="wife", domestic_violence=False, needs=["divorce"])
case("நான் இந்து, என் கணவர் என்னை அடிக்கவில்லை, விவாகரத்து வேண்டும்", law="hindu", claimant="wife", domestic_violence=False, needs=["divorce"])
case("நான் இந்து, அடிப்படையில் விவாகரத்து வேண்டும்", law="hindu", needs=["divorce"])
case("mera pati mujhe maarta hai, hum hindu hain, talaq chahiye", law="hindu", claimant="wife", domestic_violence=True, needs=["divorce", "protection"])
# paraphrases the lexicon cannot see (only the small model can add these, as suggestions)
case("He taunts me daily and makes my life miserable", tent={"ground": "cruelty"})
case("My husband has been seeing another woman for two years", claimant="wife", tent={"ground": "adultery"})
case("She has gone back to her parents and refuses to come back", tent={"ground": "desertion"})
case("my husband settled in London after marriage", claimant="wife", tent={"respondent_abroad": True})
case("We are both fine to part ways peacefully", tent={"mutual_consent": True})
case("The family court has already granted us a divorce", tent={"divorce_status": "decreed"})
case("He has taken me to court and the hearing is next month", tent={"divorce_status": "pending"})
case("I am a housewife without any income", tent={"claimant_can_self_maintain": False})
case("He is unemployed", tent={"respondent_has_means": False})
case("He owns two shops and a house", tent={"respondent_has_means": True})
case("mere pati mujhe peette hain", claimant="wife", tent={"domestic_violence": True})
case("wo videsh mein job karta hai", tent={"respondent_abroad": True})
case("கணவர் என்னை அடிக்கடி கை நீட்டுகிறார்", tent={"domestic_violence": True})
case("என் கணவர் வேறொரு பெண்ணோடு பழகுகிறார்", claimant="wife", tent={"ground": "adultery"})
case("our nikah was held at home, he left me", ground="desertion", tent={"law": "muslim"})
case("we got married in a church and he beats me", domestic_violence=True, needs=["protection"], tent={"law": "christian"})
# controls: nothing should be extracted
case("Hello, I need some help")
case("I live in Chennai and we have two children")
case("What is the process and how long will it take?")
case("நன்றி, வணக்கம்")
case("मुझे मदद चाहिए")
